// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tour_De_France.Models;

namespace Tour_De_France.Migrations
{
    [DbContext(typeof(EventDbContext))]
    [Migration("20220523091542_Tour_De_France")]
    partial class Tour_De_France
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Tour_De_France.Models.Deltager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("VIP")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Deltagere");
                });

            modelBuilder.Entity("Tour_De_France.Models.Event", b =>
                {
                    b.Property<int>("Time")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Eid")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Mobil")
                        .HasColumnType("int");

                    b.Property<int>("People")
                        .HasColumnType("int");

                    b.HasKey("Time");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Tour_De_France.Models.Musiktelt", b =>
                {
                    b.Property<int>("Mid")
                        .HasColumnType("int");

                    b.Property<string>("Band")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Drinks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("Mid");

                    b.ToTable("Musiktelte");
                });

            modelBuilder.Entity("Tour_De_France.Models.Parking_plads", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Free")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ParkingPlads");
                });

            modelBuilder.Entity("Tour_De_France.Models.Spisetelt", b =>
                {
                    b.Property<int>("Sid")
                        .HasColumnType("int");

                    b.Property<string>("Drinks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Food")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("Sid");

                    b.ToTable("Spisetelte");
                });

            modelBuilder.Entity("Tour_De_France.Models.Togafgang", b =>
                {
                    b.Property<int>("Tid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ArrivalK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArrivalN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartureK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartureN")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Tid");

                    b.ToTable("Togafgange");
                });

            modelBuilder.Entity("Tour_De_France.Models.Tribune", b =>
                {
                    b.Property<int>("Tid")
                        .HasColumnType("int");

                    b.Property<int>("Time")
                        .HasColumnType("int");

                    b.HasKey("Tid");

                    b.ToTable("Tribuner");
                });

            modelBuilder.Entity("Tour_De_France.Models.VIPMenu", b =>
                {
                    b.Property<string>("Titel")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Titel");

                    b.ToTable("VIPs");
                });
#pragma warning restore 612, 618
        }
    }
}
